name: sms_sync
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  network_info_plus: ^8.1.0
  path_provider: ^2.1.6
  permission_handler: ^12.0.3
  shared_preferences: ^2.5.5
  telephony:
    git:
      url: https://github.com/danbeyene/Telephony.git
      ref: 4b45dadd6f4239361fb3cf789ce7d8435c181af3
  multicast_dns: ^0.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/web/
