name: Flutter APK Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.23.0
        with:
          channel: stable
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Rename APK to include version
        run: |
          mkdir -p renamed
          VERSION="${{ github.ref_name }}"  # e.g. v0.2.1
          mv build/app/outputs/flutter-apk/app-release.apk renamed/sms_sync_${VERSION}.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Automated Flutter release.

            Version: ${{ github.ref_name }}
          files: renamed/sms_sync_${{ github.ref_name }}.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}